FROM eclipse-temurin:21-jdk
WORKDIR /app
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
COPY . .
RUN ./mvnw dependency:go-offline
CMD ["./mvnw", "spring-boot:run"]
EXPOSE 8080
